DROP TABLE IF EXISTS users;

CREATE TABLE orders (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name_first VARCHAR(512) NOT NULL,
  name_last VARCHAR(512) NOT NULL,
  email VARCHAR(256) NOT NULL,
  username VARCHAR(512) NOT NULL,
  pass VARCHAR(512) NOT NULL,
)
